import { Ledger } from '../src/ledger/ledger.ts';
import { resolveConfig } from '../src/core/config.ts';
const l = new Ledger(resolveConfig().ledgerPath);
const tasks = l.listTasks();
console.log(`  ${tasks.length} tasks`);
for (const t of tasks.slice(0, 4)) console.log(`   [${t.status}] ${t.title.slice(0, 68)}`);
console.log(`   ... and ${Math.max(0, tasks.length - 4)} more`);
const msgs = l.inbox('posy', false);
console.log(`\n  Posy's unread mail: ${msgs.length}`);
if (msgs[0]) console.log(`   from ${msgs[0].from}: ${msgs[0].body.slice(0, 90)}...`);
l.close();
